services:
  cli-proxy-api:
    image: ${CLI_PROXY_IMAGE:-eceasy/cli-proxy-api:latest}
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-dev}
        COMMIT: ${COMMIT:-none}
        BUILD_DATE: ${BUILD_DATE:-unknown}
    container_name: cli-proxy-api
    # env_file:
    #   - .env
    environment:
      DEPLOY: ${DEPLOY:-}
      MANAGEMENT_PASSWORD: ${MANAGEMENT_PASSWORD:-6987139899}
      CLI_PROXY_RUNTIME_CONFIG: ${CLI_PROXY_RUNTIME_CONFIG:-/CLIProxyAPI/data/config.yaml}
    ports:
      - "8317:8317"
    volumes:
      - ${CLI_PROXY_CONFIG_DIR:-./data}:/CLIProxyAPI/data
      - ${CLI_PROXY_AUTH_PATH:-./auths}:/root/.cli-proxy-api
      - ${CLI_PROXY_LOG_PATH:-./logs}:/CLIProxyAPI/logs
    restart: unless-stopped
